# Numpy Basics  <hr style = "border:2.5px solid #F22007"></hr>


Data Analyst: Christian June G. Mondroy <br>
Department: Electrical Engineering

In [96]:
# imports and packages
import numpy as np
from scipy import stats

# 1D Array

In [97]:
array_1d = np.array([1,2,3])
array_1d

array([1, 2, 3])

# 2D Array

In [98]:
array_2d = np.array([
    [1,2,3],
    [4,5,6]
])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
array_2d = array_2d.T

In [100]:
array_2d

array([[1, 4],
       [2, 5],
       [3, 6]])

In [101]:
# add by row
np.sum(array_2d, axis=0)

array([ 6, 15])

In [102]:
# add by colomn
np.sum(array_2d, axis=1)

array([5, 7, 9])

# Measures of Central Tendency

In [103]:
fruits = np.array([120,60,85,150,200])
fruits

array([120,  60,  85, 150, 200])

In [104]:
fruits_mean= np.mean(fruits)
fruits_mean

np.float64(123.0)

In [105]:
median_fruits = np.median(fruits)
median_fruits

np.float64(120.0)

In [106]:
mode_fruits = stats.mode(fruits)
mode_fruits

ModeResult(mode=np.int64(60), count=np.int64(1))

# Jaguar vs Panther

## Jaguar

In [107]:
Jaguar = np.array([10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8])
Jaguar

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [108]:
Jaguar_mean= np.mean(Jaguar)
Jaguar_mean

np.float64(9.399999999999999)

In [109]:
median_Jaguar = np.median(Jaguar)
median_Jaguar

np.float64(9.8)

In [110]:
mode_Jaguar = stats.mode(Jaguar)
mode_Jaguar

ModeResult(mode=np.float64(9.8), count=np.int64(2))

In [111]:
max_Jaguar = np.max(Jaguar)
min_Jaguar = np.min(Jaguar)

range_jag = max_Jaguar - min_Jaguar
range_jag

np.float64(8.0)

In [112]:
# Q1
q1_jag = np.percentile(Jaguar, 25)
q1_jag

np.float64(9.4)

In [113]:
# Q2
q2_jag = np.percentile(Jaguar, 50)
q2_jag

np.float64(9.8)

In [114]:
# Q3
q3_jag = np.percentile(Jaguar, 75)
q3_jag

np.float64(10.45)

In [115]:
# IQR
iqr_jag = q3_jag - q1_jag
iqr_jag

np.float64(1.049999999999999)

In [116]:
# Variance
vari_jag = np.var(Jaguar,ddof=1)
vari_jag

np.float64(4.86)

In [117]:
# Standard Deviation
std_jag = np.std(Jaguar,ddof=1)
std_jag

np.float64(2.2045407685048604)

## Panther

In [118]:
Panther = np.array([10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1])
Panther

array([10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1])

In [119]:
Panther_mean= np.mean(Panther)
Panther_mean

np.float64(10.75)

In [120]:
median_Panther = np.median(Panther)
median_Panther

np.float64(9.55)

In [121]:
mode_Panther = stats.mode(Panther)
mode_Panther

ModeResult(mode=np.float64(9.1), count=np.int64(3))

In [122]:
max_Panther = np.max(Panther)
min_Panther = np.min(Panther)

range_jag = max_Panther - min_Panther
range_jag

np.float64(10.9)

In [129]:
# Q1
q1_panth = np.percentile(Panther, 25)
q1_panth

np.float64(9.125)

In [124]:
# Q2
q2_panth = np.percentile(Panther, 50)
q2_panth

np.float64(9.55)

In [125]:
# Q3
q3_panth = np.percentile(Panther, 75)
q3_panth

np.float64(10.625)

In [126]:
# IQR
iqr_panth = q3_panth - q1_panth
iqr_panth

np.float64(1.5)

In [127]:
# Variance
vari_panth = np.var(Panther,ddof=1)
vari_panth

np.float64(11.082777777777777)

In [128]:
# Standard Deviation
std_panth = np.std(Panther,ddof=1)
std_panth

np.float64(3.3290806204983645)