# Numpy Basics  <hr style = "border:2.5px solid #F22007"></hr>


Data Analyst: Christian June G. Mondroy <br>
Department: Electrical Engineering

In [9]:
# imports and packages
import numpy as np
from scipy import stats

# Measures of Central Tendency

In [5]:
fruits = np.array([120,60,85,150,200])
fruits

array([120,  60,  85, 150, 200])

In [ ]:
fruits_mean= np.mean(fruits)
fruits_mean

np.float64(123.0)

In [ ]:
median_fruits = np.median(fruits)
median_fruits

np.float64(120.0)

In [10]:
mode_fruits = stats.mode(fruits)
mode_fruits

ModeResult(mode=np.int64(60), count=np.int64(1))

In [14]:
Jaguar = np.array([10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8])
Jaguar

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [16]:
Jaguar_mean= np.mean(Jaguar)
Jaguar_mean

np.float64(9.399999999999999)

In [20]:
median_Jaguar = np.median(Jaguar)
median_Jaguar

np.float64(9.8)

In [21]:
mode_Jaguar = stats.mode(Jaguar)
mode_Jaguar

ModeResult(mode=np.float64(9.8), count=np.int64(2))

In [15]:
Panther = np.array([10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1])
Panther

array([10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1])

In [17]:
Panther_mean= np.mean(Panther)
Panther_mean

np.float64(10.75)

In [18]:
median_Panther = np.median(Panther)
median_Panther

np.float64(9.55)

In [22]:
mode_Panther = stats.mode(Panther)
mode_Panther

ModeResult(mode=np.float64(9.1), count=np.int64(3))